image: node:14.18

stages:
  - build
  - test
  - deploy staging
  - deploy production

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build website:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build

.test app:
  stage: test
  script:
    - ls
    - npm run unit:test

serious test:
  stage: test
  extends: .test app # we can use already existing template if exists - see above job prefixed with dot - dot means that job is hidden so it won't run unless it's used as a extension

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: https://test-cicd-gitlab-alle-staging.surge.sh
  script:
    - npm install --global surge
    - surge --project ./build --domain test-cicd-gitlab-alle-staging.surge.sh

deploy production:
  stage: deploy production
  environment:
    name: staging
    url: https://test-cicd-gitlab-alle-staging.surge.sh
  script:
    - npm install --global surge
    - surge --project ./build --domain test-cicd-gitlab-alle.surge.sh
